version: '3.9'
services:
  django:
    container_name: django
    build: ./movies_admin
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - static:/opt/app/static
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app_network
    entrypoint: ./entrypoint.sh

  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - data_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
    networks:
      - app_network

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static:/data/static
    depends_on:
      - django
    ports:
      - "80:80"
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    networks:
      - app_network

volumes:
  data_db:
  static:

networks:
  app_network:
    driver: bridge
